services:
  - type: web
    name: telegram-results-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
